# ===============================
# = SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/api}

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    sk.janobono.emergency: ${LOG_LEVEL:debug}

# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: emergency-services-dashboard-be

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app}
    username: ${DB_USER:app}
    password: ${DB_PASS:app}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
